DROP DATABASE IF EXISTS chatDB;
CREATE DATABASE chatDB;

CREATE TABLE users(
  id INTEGER(15) AUTO_INCREMENT NOT NULL,
  userId INTEGER(10),
  PRIMARY KEY (id)
);

CREATE TABLE chatrooms(
  id INTEGER(15) AUTO_INCREMENT NOT NULL,
  chatroomid Integer(10),
  PRIMARY KEY (id)
);

